### PR TITLE
Feature/static html generator

### PR DESCRIPTION
**Pull request by punalsc**
Hi @gtvj ,

could you have a look at this PR.

Thanks

### CODE REVIEW

**Comment by gtvj** [comment]
Hi @punalsc, 

I'll start with an initial review of the look and feel and, once these issues have been addressed, I'll do a code review. 

# Sign in form

- [x] There's a styling problem with email address error message on the 'Sign in' form

Screenshot 2019-03-28 at 16 37 19

- [x] There's a styling problem with email address error message on the 'Sign in' form

Screenshot 2019-03-28 at 16 39 03

- [x] There's an alignment issue with the "Can't seem to find your account" message

Screenshot 2019-03-28 at 16 40 06

# Registration form

- [x] Can we remove the 'bold' styling from the 'Verification is necessary...' message and make it look like a standard notification message (with the background and border-left)

Screenshot 2019-03-28 at 16 41 37

- [x] The 'Create' button has the disabled attribute applied. Can we use this to style it so that it is clear to the user that they can't use it? 

Screenshot 2019-03-28 at 16 44 45

- [x] There's an issue with the error message on email address (it's got a border-right)

Screenshot 2019-03-28 at 16 51 25

@punalsc - I'm going to pause this review at this stage while you fix the issues outlined above. Once these are fixed, please give me a nudge and re-submit this as a PR.

**Review by gtvj — CHANGES_REQUESTED** [review]
Hi @punalsc - could you fix the changes I've identified (and any others you can see by going through the key user journeys, and then re-submit this to me as a PR). I'll then do a further review of the UI and proceed to look at the code. Many thanks.

**Comment by punalsc** [comment]
> Hi @punalsc - could you fix the changes I've identified (and any others you can see by going through the key user journeys, and then re-submit this to me as a PR). I'll then do a further review of the UI and proceed to look at the code. Many thanks.

Hi @gtvj ,
I have made the above changes as per your request.

**Comment by gtvj** [comment]
Screenshot 2019-03-29 at 17 09 24

- [x] There seems to be a small difference in the styling for outlines and error message (we're using a `padding: 3px` for most TNA forms but this seems to have more padding at the bottom). I've had a bit of a play in dev tools and found it helped to set the exiting rule in `main.css` to - it also seems this might help other messages.

```css
#api .error.itemLevel>p { margin: 0; }
```

**Comment by gtvj** [comment]
There are a few things (shown below) that don't seem quite right once you've provided a verification email. 

Screenshot 2019-03-29 at 18 23 41

- [x] Can the 'Verification code has been sent to your inbox...' message be styled as a confirmation message (using the normal box/border styles)
- [x] Can we fix the spacing between the 'Verification code' and the text field that appears above it

**Comment by gtvj** [comment]
If you enter an incorrect verification code (or fail to provide one) 

Screenshot 2019-03-29 at 18 26 34

- [x] Can we fix the margin between the dotted header and the error box

**Comment by punalsc** [comment]
Hi @gtvj ,

I have further made some styling as per your request. Could you kindly have a look?

Thanks

**Pull request closed without merging**
